FROM public.ecr.aws/lambda/python:3.8

# lambda_end_of_topic.py

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY lambda_end_of_topic.py ${LAMBDA_TASK_ROOT}
COPY end_of_topic_detector.py ${LAMBDA_TASK_ROOT}
COPY get_openai_key.py ${LAMBDA_TASK_ROOT}

# Copy API keys from folders
COPY OPENAI_API_KEY/OPENAI_API_KEY_MINDHIVE.txt ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_end_of_topic.lambda_end_of_topic" ]