name: Deploy to ECR

on:
   push:
    branches: 
     - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2 # Replace with your AWS region which appears to be ap-southeast-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 339713113095.dkr.ecr.ap-southeast-2.amazonaws.com/test-ecr

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t your-image:latest .
        docker tag your-image:latest 339713113095.dkr.ecr.ap-southeast-2.amazonaws.com/test-ecr:latest
        docker push 339713113095.dkr.ecr.ap-southeast-2.amazonaws.com/test-ecr:latest
