name: Deploy to ECR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2 # Replace with your AWS region which appears to be ap-southeast-2

    - name: Login to AWS ECR
      run: |
        AWS_ECR_PASSWORD=$(aws ecr get-login-password --region ap-southeast-2)
        echo $AWS_ECR_PASSWORD | docker login --username AWS --password-stdin 339713113095.dkr.ecr.ap-southeast-2.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build, tag, and push image to Amazon ECR
      run: |
        docker build -t your-image:latest .
        docker tag your-image:latest 339713113095.dkr.ecr.ap-southeast-2.amazonaws.com/test-ecr:latest
        docker push 339713113095.dkr.ecr.ap-southeast-2.amazonaws.com/test-ecr:latest
